source: content
output: public
paths:
  uploads: uploads
  static: public
  collections: content
  data: data
collections_config:
  pages:
    path: content
    output: false
    icon: notes
    _editables:
      text: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
